# Generated by Django 3.1.7 on 2021-10-16 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d1',
            old_name='address',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='d1',
            old_name='mobile',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='d1',
            name='name',
        ),
    ]
