# Generated by Django 3.1.7 on 2021-10-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_d2'),
    ]

    operations = [
        migrations.CreateModel(
            name='d3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=122)),
                ('Street_name', models.CharField(max_length=122)),
                ('Near_location', models.CharField(max_length=122)),
            ],
        ),
    ]
