# Generated by Django 3.1.7 on 2021-10-18 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_d3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='d3',
        ),
    ]
